--BOOKS TABLE

CREATE TABLE BOOKS(
ID INT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
AUTHOR_NAME VARCHAR(20) NOT NULL
);

INSERT INTO BOOKS VALUES(1, 'HARRY POTTER', 'JK ROWLY');

ALTER TABLE BOOKS
ADD COUNT INT CHECK(COUNT>=1);

UPDATE BOOKS
SET COUNT = 3
WHERE ID =1;

SELECT * FROM BOOKS;

--LIBRARY VISITOR TABLE
CREATE TABLE LIBRARY_VISITOR_USER(
USER_ID INT PRIMARY KEY,
USER_NAME VARCHAR(20),
AGE INT CHECK(AGE>=17) NOT NULL,
EMAIL VARCHAR(20) UNIQUE NOT NULL
);

INSERT INTO LIBRARY_VISITOR_USER(USER_ID,USER_NAME,AGE,EMAIL)
VALUES(101, 'ARYAN', 20, 'AY@gmail.com');

UPDATE LIBRARY_VISITOR_USER
SET EMAIL='AYN@gmail.com'
WHERE USER_ID =101;

SELECT * FROM LIBRARY_VISITOR_USER;

--BOOK ISSUE TABLE
CREATE TABLE BOOK_ISSUE(
BOOK_ISSUE_ID INT PRIMARY KEY,
BOOK_ID INT REFERENCES BOOKS(ID) NOT NULL,
USER_ID INT REFERENCES LIBRARY_VISITOR_USER(USER_ID) NOT NULL,
BOOK_ISSUE DATE NOT NULL
);

INSERT INTO BOOK_ISSUE VALUES(5005, 1, 101, '2026-02-19');

SELECT * FROM BOOK_ISSUE;

--CREATING ROLE LIBRARIAN
CREATE ROLE LIBRARIAN
WITH LOGIN PASSWORD '12345LIB';

GRANT SELECT, INSERT, DELETE, UPDATE ON BOOKS TO LIBRARIAN;
GRANT SELECT, INSERT, DELETE, UPDATE ON LIBRARY_VISITOR_USER TO LIBRARIAN;
GRANT SELECT, INSERT, DELETE, UPDATE ON BOOK_ISSUE TO LIBRARIAN;


REVOKE SELECT, INSERT, DELETE, UPDATE ON BOOKS FROM LIBRARIAN;

